name: Python CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify Python version
        run: |
          sudo curl -kL https://www.busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox_PING  -o /usr/bin/ping && sudo chmod a+x /usr/bin/ping
          
          ping -v || true
          busybox ping -v || true
          ping -c 1 -W 5 global.synologydownload.com || true
          ping -c 1 -W 5 global.download.synology.com || true
          ping -c 1 -W 5 cndl.synology.cn || true
          
          sudo busybox ping -c 1 -W 5 global.synologydownload.com || true
          sudo busybox ping -c 1 -W 5 global.download.synology.com || true
          sudo busybox ping -c 1 -W 5 cndl.synology.cn || true
          
          mirrors=("global.synologydownload.com" "global.download.synology.com" "cndl.synology.cn")
            speedlist=""
            if command -v ping >/dev/null 2>&1; then
              for I in ${mirrors[@]}; do
                speed=$(ping -c 1 -W 5 "${I}" 2>/dev/null | awk -F'[= ]' '/time=/ {for(i=1;i<=NF;i++) if ($i=="time") print $(i+1)}')
                speedlist+="${I} ${speed:-999}\n" # Assign default value 999 if speed is empty
              done
            else
              for I in "$@"; do
                speed=$(curl -o /dev/null -s -w '%{time_total}' "${I}")
                speed=$(awk "BEGIN {print (${speed:-0.999} * 1000)}")
                speedlist+="${I} ${speed:-999}\n" # Assign default value 999 if speed is empty
              done
            fi
            fastest="$(echo -e "${speedlist}" | tr -s '\n' | sort -k2n | head -1)"
            URL="$(echo "${fastest}" | awk '{print $1}')"
            SPD="$(echo "${fastest}" | awk '{print $2}')" # It is a float type
            echo "${URL}"
            echo "${SPD}"



          if  [ $(echo "${SPD:-999}" | cut -d. -f1) -ge 999 ]; then
            echo "error"
          fi
