#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: Redpill Build (schedule)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Find schedule issues
        id: find-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'find-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
#          issue-state: 'open'
          title-includes: 'custom'
          label-includes: 'schedule'

      - name: Generate build matrix
        id: set-matrix
        uses: actions/github-script@v6
        with:
          script: |
            let matrix = {};
            matrix.issues = ${{ steps.find-issues.outputs.issues }};
            core.setOutput("matrix",JSON.stringify(matrix));


  build:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Loop on issues
        run: |
          echo "number:     ${{ matrix.issues.number }}"
          echo "issueauth:  ${{ matrix.issues.auth }}"
          echo "issuetitle: ${{ matrix.issues.title }}"
          echo "issuebody:  ${{ matrix.issues.body }}"
        
      - name: Loop on issues
        uses: ./.github/workflows/custom
        with:
          issuenumber: ${{ matrix.issues.number }}
          issueauth: ${{ matrix.issues.auth }}
          issuetitle: ${{ matrix.issues.title }}
          issuebody: ${{ matrix.issues.body }}

