#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: Redpill Build (schedule)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Find schedule issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'find-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          title-includes: 'custom'
          label-includes: 'schedule'


      - name: Loop on issues
        uses: ./.github/workflows/custom.yml
        with:
          issuenumber: ${{ fromJson(steps.findissueid.outputs.issues)[0].number }}
          issueuser: ${{ fromJson(steps.findissueid.outputs.issues)[0].auth }}
          issuetitle: ${{ fromJson(steps.findissueid.outputs.issues)[0].title }}
          issuebody: ${{ fromJson(steps.findissueid.outputs.issues)[0].body }}

